export const COMMAND_ALIASES = new Map([
  ["p", "play"],
  ["reproducir", "play"],
  ["pausa", "pause"],
  ["pausar", "pause"],
  ["reanudar", "resume"],
  ["continuar", "resume"],
  ["saltar", "skip"],
  ["next", "skip"],
  ["detener", "stop"],
  ["parar", "stop"],
  ["salir", "leave"],
  ["disconnect", "leave"],
  ["cola", "queue"],
  ["q", "queue"],
  ["np", "nowplaying"],
  ["sonando", "nowplaying"],
  ["ayuda", "help"],
  ["comandos", "help"],
]);
